# Generated by Django 4.1.7 on 2023-03-23 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="((?=.*[a-z])(?=.*[A-Z]))|((?=.*[A-Z])(?=.*[a-z]))|(?=.*[a-z])|(?=.*[A-Z])"
                            )
                        ],
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="((?=.*[a-z])(?=.*[A-Z]))|((?=.*[A-Z])(?=.*[a-z]))|(?=.*[a-z])|(?=.*[A-Z])"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=50, null=True, unique=True)),
                ("phone_number", models.CharField(max_length=30, null=True)),
                (
                    "image",
                    models.ImageField(
                        default="profile/default.jpg", null=True, upload_to="profile/"
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=30, null=True)),
                ("admin", models.BooleanField(default=False)),
                ("staff", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "usertype",
                    models.CharField(
                        choices=[
                            ("DeliveryPerson", "DeliveryPerson"),
                            ("DressManager", "DressManager"),
                            ("SchoolAdmin", "SchoolAdmin"),
                            ("SystemAdmin", "SystemAdmin"),
                        ],
                        default="Admin",
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
